name-template: 'Quantum Security v$NEXT_PATCH_VERSION'
template: |
  ## Quantum Security Release Notes
  $CHANGES
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
categories:
  - title: 'Enhancements'
    labels:
      - enhancement
  - title: 'Bug Fixes'
    labels:
      - bug
