# .pre-commit-config.yaml

repos:
  # Black – автоформатирование кода
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Black (format)
        language_version: python3

  # Ruff – линтинг (pre-commit поддерживается через отдельный репо)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: Ruff (lint)
        args: ["--fix"]
        language_version: python3

  # isort – проверка и сортировка импортов
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort (check imports)
        args: ["--profile", "black"]
        language_version: python3


  # Проверка YAML, удаление лишних пробелов, финальная пустая строка
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: YAML syntax check
      - id: end-of-file-fixer
        name: Ensure file ends with newline
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: mixed-line-ending
        name: Unix line endings
        args: ["--fix=lf"]
        files: ^scripts/.*
      - id: check-executables-have-shebangs
        name: Executable has shebang
        files: ^scripts/.*

  # Mypy – статическая проверка типов (только для кода внутри пакета, не затрагиваем скрипты)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy (type check)
        additional_dependencies: ["types-requests"]
        language_version: python3
        files: ^src/zilant_prime_core/(?!scripts/).*\.py$
