rules:
  - id: no-hardcoded-crypto-key
    message: Do not hardcode cryptographic keys
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern-regex: "(?i)(key|secret)\\w*\\s*=\\s*b?[\\\"'][^\\\"']{32,}[\\\"']"
      - pattern-regex: "(?i)(key|secret)\\w*\\s*=\\s*b?[\\\"'][^\\\"']*[\\\"']\\s*\\*\\s*\\d+"
  - id: require-os-urandom
    message: Use os.urandom() or secrets module for cryptography
    severity: WARNING
    languages: [python]
    patterns:
      - pattern-either:
          - pattern: random.random(...)
          - pattern: random.randint(...)
      - pattern-either:
          - pattern-inside: |
              import hashlib
              ...
          - pattern-inside: |
              import cryptography
              ...
          - pattern-inside: |
              from cryptography import $X
              ...
