# SPDX-FileCopyrightText: 2025 Zilant Prime Core contributors
# SPDX-License-Identifier: MIT

############################
#       Ruff config        #
############################
line-length    = 100
target-version = "py310"

# базовый набор + «умные» проверки modern-python / arg / numpy-совместимость
select   = ["E", "F", "B", "I", "N", "UP", "ARG"]
# что автоматически чинить (`ALL` – чинит всё, что умеет Ruff)
fixable  = ["ALL"]

# пути, которые Ruff должен анализировать
src = ["src", "tests"]

# что пропускать (дублирует .gitignore, но Ruff читает быстрее)
exclude = [
    ".git",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    "build",
    "dist",
]
