name: zilant-prime-core
base: core22
version: "{{ version }}"
summary: "Zilant Prime Core — secure container CLI"
description: |
  CLI-инструмент для шифрования, упаковки и мониторинга.
grade: stable
confinement: strict

parts:
  zilant:
    plugin: python
    source: .
    python-version: python3
    stage-packages:
      - libssl-dev

apps:
  zilant:
    command: bin/zilant
    plugs: [network, home, removable-media]
