import hashlib


def generate_posw(seed: bytes, steps: int) -> bytes:
    """Generate proof of work by applying SHA-256 `steps` times."""
    h = seed
    for _ in range(steps):
        h = hashlib.sha256(h).digest()
    return h


def verify_posw(proof: bytes, seed: bytes, steps: int) -> bool:
    """Verify proof of work generated by `generate_posw`."""
    expected = generate_posw(seed, steps)
    return proof == expected
