# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 Zilant Prime Core contributors

name: Auto Changelog

on:
  pull_request:
    paths:
      - 'tools/auto_changelog.py'
      - '.github/workflows/changelog.yml'
      - '**/*.py'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate changelog
        run: python tools/auto_changelog.py

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: auto-changelog
          path: CHANGELOG_AUTO.md
