name: Fuzz Testing

on:
  push:
    paths:
      - 'crypto/aead.py'
      - 'vdf/phase_vdf.py'
      - 'utils/self_watchdog.py'
  pull_request:
    paths:
      - 'crypto/aead.py'
      - 'vdf/phase_vdf.py'
      - 'utils/self_watchdog.py'

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - name: Install dependencies
        run: |
          pip install atheris
          pip install -e .[dev]

      - name: Run Atheris fuzzers
        run: |
          python -m atheris --output=fuzz-report.txt crypto/aead.py
          python -m atheris --output=fuzz-report.txt vdf/phase_vdf.py
          python -m atheris --output=fuzz-report.txt utils/self_watchdog.py
        continue-on-error: true

      - name: Upload fuzz report
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-report
          path: fuzz-report.txt
