name: CI Fuzz
on:
  push:
    branches: [ main, ci-check-ready ]
  pull_request:
    branches: [ main, ci-check-ready ]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: pip install -e .[dev]
      - name: Run atheris fuzzing
        run: python tools/atheris_fuzz.py --ci -max_total_time=30 > fuzz-report.txt
      - uses: actions/upload-artifact@v4
        with:
          name: fuzz-report
          path: fuzz-report.txt
