# SPDX-FileCopyrightText: 2025 Zilant Prime Core contributors
# SPDX-License-Identifier: MIT
name: Gitleaks Secrets Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks scan
        uses: zricethezav/gitleaks-action@v2.3.2
        with:
          args: >-
            detect --source .
                   --config-path=.gitleaks.toml
                   --redact
                   --report-format sarif
                   --report-path gitleaks.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
