name: LFS Integrity
on: [push, pull_request]

jobs:
  lfs-integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Verify LFS assets
        run: |
          git lfs pull --exclude="" --include="*"
          shopt -s nullglob
          for f in docs/assets/*.{gif,png,svg,mp4}; do
            test -f "$f" && file "$f"
          done
