name: pytest
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      extras:
        required: false
        type: string
        default: ""
      os:
        required: true
        type: string
jobs:
  run-tests:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Disable LFS smudge
        run: echo "GIT_LFS_SKIP_SMUDGE=1" >> $GITHUB_ENV
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Install deps
        shell: bash {0}
        run: |
          extras="${{ inputs.extras }}"
          if [ -n "$extras" ]; then
            pip install -e ".[$extras]"
          else
            pip install -e .
          fi
      - name: Debug
        run: |
          echo '>>> PYTEST STARTING'
          which pytest
      - name: Pytest
        run: pytest -q -m "not slow"
