# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 Zilant Prime Core contributors

name: Secret Scan

on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.yml'
      - '**/*.sh'
      - 'tools/secret_scanner.py'
      - '.github/workflows/secret-scan.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run secret scanner
        run: python tools/secret_scanner.py

      - name: Upload secret scan report
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-report
          path: secret_leak_report.md
