name: Security Suite
on:
  pull_request:

jobs:
  # 1 Semgrep
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: pip install semgrep
      - name: Run Semgrep
        run: semgrep scan --config .semgrep/custom --error    # ← новая CLI

  # 2 Trivy
  depscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.19.0                # без префикса v
        with:
          scan-type: fs
          format: table

  # 3 Gitleaks
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 4 Наши pytest-тесты
  custom-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: pip install -r requirements-dev.txt tabulate
      - run: pytest -q                               # без несуществующего каталога

  # 5 CycloneDX SBOM
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        uses: CycloneDX/gh-generate-sbom@v1          # корректное имя action
        with:
          output: sbom.xml
      - uses: actions/upload-artifact@v4             # v4 — актуальная

