name: Security Suite

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  semgrep:
    name: Static code analysis (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v3
        with:
          config: .semgrep/custom

  trivy:
    name: Dependency scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@v0.9.0
        with:
          scan-type: fs
          format: json
          output: trivy-report.json

  gitleaks:
    name: Scan secrets (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --path=. --exit-code 1

  custom-tests:
    name: Run custom security tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Run security tests
        run: pytest tests/security --maxfail=1 --disable-warnings -q

  sbom:
    name: Generate SBOM (CycloneDX)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate SBOM
        uses: CycloneDX/gh-action-generate-sbom@v2
        with:
          output: sbom.xml
