# .github/workflows/security.yml
name: Security Suite

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  semgrep:
    name: Static code analysis (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install semgrep
      - run: semgrep --config .semgrep/custom

  trivy:
    name: Dependency scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@v0.32.0
        with:
          format: 'table'
          exit-code: '1'

  gitleaks:
    name: Scan secrets (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zricethezav/gitleaks-action@v2
        with:
          args: --path=.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  custom-tests:
    name: Run custom security tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run: pytest --maxfail=1 --disable-warnings -q

  sbom:
    name: Generate SBOM (CycloneDX CLI)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install cyclonedx-bom
      - run: cyclonedx-py requirements --output sbom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
